#\!/bin/zsh
autoload -U colors && colors

echo ""
print -P "%F{39}╭─────────────────────────────────────────────────────────────────────╮%f"
print -P "%F{39}│%f  %F{114}⚡%f %F{39}Life In Hand Claude Development Environment%f  %F{114}⚡%f  %F{39}│%f"
print -P "%F{39}╰─────────────────────────────────────────────────────────────────────╯%f"
echo ""
print -P "%F{220}📁%f %F{green}Project directory:%f %F{cyan}/workspace%f"
echo ""
print -P "%F{114}🔧 Available commands:%f"
print -P "  %F{cyan}claude%f         : Launch Claude Code with --model sonnet"
print -P "  %F{cyan}claude-dev%f     : Launch Claude Code in project directory"
print -P "  %F{green}dev-start%f      : Start development server (npm run dev)"
print -P "  %F{green}dev-test%f       : Run tests (npm test)"
print -P "  %F{green}dev-build%f      : Build project (npm run build)"
print -P "  %F{green}dev-lint%f       : Run linting (npm run lint)"
print -P "  %F{green}dev-typecheck%f  : Run type checking (npm run typecheck)"
print -P "  %F{yellow}check%f          : Run lint and typecheck together"
echo ""
print -P "%F{red}🔒 Security & Whitelist Management:%f"
print -P "  %F{magenta}show-whitelist%f : Show all whitelisted domains (working)"
print -P "  %F{magenta}whitelist add%f  : Add domain to whitelist"
print -P "  %F{magenta}firewall-status%f: Show current firewall rules"
echo ""
print -P "%F{blue}🛠️  CLI Tools available:%f"
print -P "  %F{white}gh%f             : GitHub CLI"
print -P "  %F{white}aws%f            : AWS CLI"
print -P "  %F{white}uv%f             : Python package manager"
print -P "  %F{white}python%f         : Python 3"
print -P "  %F{white}tree%f           : Directory tree view"
echo ""
print -P "%F{214}🐚 Shell Features:%f"
print -P "  %F{green}Enhanced ZSH%f   : Beautiful prompt with git integration"
print -P "  %F{green}Smart aliases%f  : All commands have emoji feedback"
print -P "  %F{green}Auto-navigation%f: Just type directory name to navigate"
echo ""
print -P "%F{226}💡 Pro Tips:%f"
print -P "  %F{bright-green}claude%f         → Start Claude Code with Sonnet model"
print -P "  %F{bright-green}dev-start%f      → Start development server"
print -P "  %F{bright-blue}help%f           → Show this message again"
print -P "  %F{bright-yellow}ll%f             → List files with details"
print -P "  %F{bright-magenta}src%f            → Just type directory name to navigate"
echo ""
print -P "%F{39}╭─ Happy coding\! 🚀 ────────────────────────────────────────────────╮%f"
print -P "%F{39}│%f   %F{220}Claude Code Development Environment is ready for action\!%f   %F{39}│%f"
print -P "%F{39}╰────────────────────────────────────────────────────────────────────╯%f"
echo ""
